import type { Metadata } from "next";
import {
  Playfair_Display,
  Didact_Gothic,
  League_Script,
  Geist,
} from "next/font/google";
import Navbar from "@/_components/navbar";
import "./globals.css";
import Footer from "@/_components/Home/Footer";
import FirstVisitLoader from "@/_components/FirstVisitLoader";
import { LoaderGateProvider } from "@/_components/LoaderGateProvider";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfair-display",
});

const didactGothic = Didact_Gothic({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-didact-gothic",
});

const leagueScript = League_Script({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-league-script",
});

export const metadata: Metadata = {
  title: "Dora's Designs & Decorations",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/doraDesign.webp",
    shortcut:
      "/logo/ChatGPT%20Image%20Apr%2026%2C%202026%2C%2003_52_57%20PM.png",
    apple: "/logo/ChatGPT%20Image%20Apr%2026%2C%202026%2C%2003_52_57%20PM.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        playfairDisplay.variable,
        didactGothic.variable,
        leagueScript.variable,
        "font-sans",
        geist.variable,
      )}
    >
      <head>
        <link
          rel="preload"
          href="/logo/illustration.webp"
          as="image"
          type="image/webp"
        />
      </head>
      <body className="min-h-full flex flex-col overflow-x-hidden bg-[#7E8978] text-foreground">
        <LoaderGateProvider>
          <FirstVisitLoader />
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
        </LoaderGateProvider>
      </body>
    </html>
  );
}
