import type { Metadata } from "next";
import {
  Playfair_Display,
  Didact_Gothic,
  League_Script,
} from "next/font/google";
import Navbar from "@/_components/navbar";
import "./globals.css";
import Footer from "@/_components/Home/Footer";

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfair-display",
});

const didactGothic = Didact_Gothic({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-didact-gothic",
});

const leagueScript = League_Script({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-league-script",
});

export const metadata: Metadata = {
  title: "Royal Event Consulting",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/ChatGPT%20Image%20Apr%2026%2C%202026%2C%2003_52_57%20PM.png",
    shortcut:
      "/logo/ChatGPT%20Image%20Apr%2026%2C%202026%2C%2003_52_57%20PM.png",
    apple: "/logo/ChatGPT%20Image%20Apr%2026%2C%202026%2C%2003_52_57%20PM.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${playfairDisplay.variable} ${didactGothic.variable} ${leagueScript.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black text-white overflow-x-hidden">
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
